serenity.project.name=SWAG LABS
serenity.test.root=com.swag.pe # <-- Cambiar a tu paquete raíz real

webdriver.driver = chrome
#webdriver.autodownload= true
webdriver.chrome.driver = C:/webdrivers/chrome/135/chromedriver.exe
serenity.browser.maximized = true

serenity.use.unique.browser = false
serenity.restart.browser.each.scenario=true
webdriver.wait.for.timeout=5000
serenity.timeout=5000